### ISSUE TITLE
Spec version in the file name of the bundled spec isn't available for client generation.

### ISSUE THREAD

**Issue by cheshirsky** [Backbase/backbase-openapi-tools#129]
Scenario.
I'm using BOAT 0.11.0 to:
1. Bundle the OpenAPI spec.
2. Generate client for web.

Here is the plugins section of my pom.xml:
```xml
<plugins>
    <plugin>
        <groupId>com.backbase.oss</groupId>
        <artifactId>boat-maven-plugin</artifactId>
        <version>0.11.0</version>
        <executions>
            <execution>
                <id>bundle-specs</id>
                <phase>generate-sources</phase>
                <goals>
                    <goal>bundle</goal>
                </goals>
                <configuration>
                    <input>src/main/resources</input>
                    <output>${project.build.directory}</output>
                    <versionFileName>true</versionFileName>
                </configuration>
            </execution>
        </executions>
    </plugin>
    <plugin>
        ...
    </plugin>
    <plugin>
        <groupId>com.backbase.oss</groupId>
        <artifactId>boat-maven-plugin</artifactId>
        <version>${boat-maven-plugin.version}</version>
        <executions>
            <execution>
                <id>generate-client-code</id>
                <phase>generate-sources</phase>
                <goals>
                    <goal>generate</goal>
                </goals>
                <configuration>
                    <inputSpec>${project.build.directory}/my-spec-client-api-v3.0.1.yaml</inputSpec>
                    <generatorName>boat-angular</generatorName>
                    <output>${project.build.directory}/http-module</output>
                    <additionalProperties>...</additionalProperties>
                </configuration>
            </execution>
        </executions>
    </plugin>
</plugins>
```

The first plugin call creates for me a file called *my-spec-client-api-v3.0.1.yaml* in the target folder, where 3.0.1 is the version property taken from my spec. I need it for my publishing mechanism.

The second call of the plugin (the one to generate client) don't have access to the version number, hence it's "hardcoded" in the example, which I'd like to avoid if possible.

I'd appreciate if you can advice me on how I can handle it. E.g. shall I try to restructure the pom file of mine and have 2 executions in one plugin?

**Comment by pa314159** [comment]
@cheshirsky, starting with boat-0.9.0, the goal bundle accepts the <version/> parameter.

So you can use a maven property to define the specification version.

**Comment by jjjasper** [comment]
In most projects where I use the bundler, I execute it twice: once using a fixed filename to allow other plugins to be configured, and once to generate with the correctly versioned filename for publishing. I don't like setting the version from outside of the spec because that moves the version further away from the api.

Perhaps a cool feature would be to change the boat to set a property that can be used after execution.
Eg, when I use the boat to bundle 'my-cool-client-api-v1` it creates a file `my-cool-client-api-v1.7.4` and exposes a maven project property `my-cool-client-api-v1.version` with the value `1.7.4` (or a property `my-cool-client-api-v1.filename` with value`my-cool-client-api-v1.7.4`)
